spring.application.name=demo
server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/rafcloud
spring.datasource.username=postgres
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=THIS_IS_A_32+_CHAR_SECRET_KEY_123456
app.jwt.expDays=1

app.cors.allowedOrigin=http://localhost:3000